=encoding utf8


=head1 dashpipe

B<dashpipe> is a utility for ponifying and deponifying text.

It replaces words such as 'everyone' with 'everypony'.

It either returns a ponified version of text from an input pipe, or directly from STDIN.


=head1 Installation

There are two ways to install B<dashpipe>, via a provided package, or manually.

=head2 Arch Linux

Arch linux comes with an AUR package, under L<dashpipe-git|https://aur.archlinux.org/packages/dashpipe-git/> .

Install it under pacaur, another aur frontend, or just download the PKGBUILD and do it yourself!

    $ pacaur -S dashpipe-git

=head2 Manually

B<dashpipe> comes with a handy little Makefile, so you can simply:

    $ make
    $ make install

This will make and install the man page, script itself, and license

B<dashpipe> supports the usual I<PREFIX> variable to change where it is installed. Check the Makefile itself for other options!
